"""empty message

Revision ID: 1361cf969e
Revises: None
Create Date: 2014-08-06 18:51:58.260000

"""

# revision identifiers, used by Alembic.
revision = '1361cf969e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
