"""empty message

Revision ID: 4cc83bfeec03
Revises: a1b5f542eee
Create Date: 2014-08-06 19:55:31.123000

"""

# revision identifiers, used by Alembic.
revision = '4cc83bfeec03'
down_revision = 'a1b5f542eee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('article', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('article', sa.Column('date_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'date_created')
    op.drop_column('article', 'category')
    op.drop_column('article', 'author')
    ### end Alembic commands ###
