"""empty message

Revision ID: a1b5f542eee
Revises: 1361cf969e
Create Date: 2014-08-06 19:36:28.327000

"""

# revision identifiers, used by Alembic.
revision = 'a1b5f542eee'
down_revision = '1361cf969e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
